---
# tasks file for jenkins
- name: 'Copy a dockerservice-jenkins '
  copy: {src: /home/ubuntu/pt-1/ec2-docker-swarm-prometheus-grafana-master/dockerswarm-elk-monitoring-automation/docker_service_cmd.sh, dest: /home/centos}

- name: 'Execute the script'
  command: 'sh /home/centos/docker_service_cmd.sh'
